# -*- coding: utf-8 -*-
"""Proyecto Modulo Final 5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iKCrfR9u0y5Bmpuj-a4Y8__HGbjUMOmW

#Proyecto: ANALISIS EXPLORATORIO DE DATOS PARA DECISIONES COMERCIAL

Lección 1: ANÁLISIS EXPLORATORIO DE DATOS

Lección 2: CONCEPTOS BÁSICOS DE ESTADÍSTICA DESCRIPTIVA

Lección 3: CORRELACIÓN

Lección 4: REGRESIONES LINEALES

Lección 5: ANÁLISIS VISUAL DE DATOS

Lección 6: LIBRERÍA MATPLOTLIB

Este proyecto consiste en un análisis exploratorio (EDA) realizado sobre los datos históricos de la empresa **ComercioYA**. El objetivo es comprender el comportamiento de compra de los clientes para sustentar decisiones estratégicas de negocio.

## Etapas del Proyecto
1. **Limpieza de datos:** Tratamiento de valores nulos, duplicados y outliers.
2. **Estadística descriptiva:** Análisis de tendencia central y dispersión.
3. **Correlación:** Identificación de variables con mayor impacto en el total de venta.
4. **Regresión:** Modelado lineal para predecir el comportamiento del cliente.
5. **Visualización:** Análisis profundo mediante Seaborn y Matplotlib.

## Insights Principales
* Se comentan al final
"""

# Importación de librerías

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.api as sm
from sklearn.metrics import mean_squared_error, mean_absolute_error
import os

sns.set(style="whitegrid")

# Ruta de Datasets Proyecto Final Módulo 5 - ventas_ecommerce_2025_2025

from google.colab import drive
drive.mount('/content/drive')

print("Drive montado correctamente")

ruta = "/content/drive/MyDrive/Colab Notebooks/Proyectos Final de Módulos/Proyecto Final Módulo 5/data_Proyecto final módulo 5/"

print("Archivos en la carpeta:")
print(os.listdir(ruta))

# Cargar Datasets utilizado para el análisis

ventas = pd.read_excel(ruta + "ventas_ecommerce_2025_2026.xlsx")

print("Datasets cargados correctamente")

# Exploración Inicial - Análisis Exploratorio de Datos

print("\nPrimeras filas de clientes")
print(clientes.head())

print("\nPrimeras filas de ventas")
print(ventas.head())

print("\nInformación del dataset de ventas")
print(ventas.info())

# Identificación de tipos de variables

print("Variables categóricas:")
print(df.select_dtypes(include=['object']).columns)

print("\nVariables cuantitativas:")
print(df.select_dtypes(include=['int64','float64']).columns)

print("Información general del dataset")
print(df.info())

print("\nValores faltantes por columna:")
print(df.isnull().sum())

print("\nRegistros duplicados:")
print(df.duplicated().sum())

print("\nEstadísticas descriptivas:")
print(df.describe())
df = df.replace([np.inf, -np.inf], np.nan)
df = df.dropna()
media = df["total_venta"].mean()
mediana = df["total_venta"].median()
moda = df["total_venta"].mode()[0]
varianza = df["total_venta"].var()
desviacion = df["total_venta"].std()

print("Media:", media)
print("Mediana:", mediana)
print("Moda:", moda)
print("Varianza:", varianza)
print("Desviación estándar:", desviacion)

Q1 = df["total_venta"].quantile(0.25)
Q3 = df["total_venta"].quantile(0.75)

# Rango intercuartílico
IQR = Q3 - Q1

# Límites para detectar outliers
limite_inferior = Q1 - 1.5 * IQR
limite_superior = Q3 + 1.5 * IQR

print("Límite inferior:", limite_inferior)
print("Límite superior:", limite_superior)

# Identificar valores atípicos
outliers = df[(df["total_venta"] < limite_inferior) | (df["total_venta"] > limite_superior)]

print("Cantidad de outliers:", len(outliers))

# Media con outliers
print("Media con outliers:", df["total_venta"].mean())

# Dataset sin outliers
df_sin_outliers = df[(df["total_venta"] >= limite_inferior) & (df["total_venta"] <= limite_superior)]

# Media sin outliers
print("Media sin outliers:", df_sin_outliers["total_venta"].mean())

P10 = df["total_venta"].quantile(0.10)
P90 = df["total_venta"].quantile(0.90)

print("Percentil 10:", P10)
print("Percentil 90:", P90)

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(8,5))

sns.histplot(df["total_venta"], bins=30, kde=True)

plt.title("Distribución del total de ventas")
plt.xlabel("Total de venta")
plt.ylabel("Frecuencia")

plt.show()

plt.figure(figsize=(8,5))

sns.boxplot(x=df["total_venta"])

plt.title("Boxplot del total de ventas")

plt.show()

print("Media con outliers:", df["total_venta"].mean())

df_sin_outliers = df[(df["total_venta"] >= limite_inferior) & (df["total_venta"] <= limite_superior)]

print("Media sin outliers:", df_sin_outliers["total_venta"].mean())

print("\nDatos después de limpieza:", df.shape)

"""# HALLAZGOS DEL PRIMER ANALISIS

**El dataset contiene variables cuantitativas como:**
1. Edad
2. Ingreso mensual
3. cantidad
4. Precio unitario
5. Total de venta

**Se identificaron variables categóricas como:**
1. Género
2. Región
3. Canal de venta
4. Nombre categoria
5. País



**El primer análisis permitió detectar valores faltantes los que fueron tratados en la etapa de limpieza de datos.**

#_______________________________________________________________________________

**Las estadísticas descriptivas presenta variabilidad, esto se debe por el nivel de comportamiento por parte de los clientes en las compras.**
La diferencia entre la media y la mediana se debe al valor alto de algunas transacciones que elevan el promedio de ventas.
La desviación estándar refleja gran dispersión de los datos.
Al eliminar los outlier se observa una reducción de la media, esto se enlaza con lo mencionado, debido a que algunas transacciones han elevado el promedio de las ventas. El boxplot muestra una distribución asimétrica hacia la derecha, lo que indica la presencia de ventas de alto monto que aumentan el promedio general. El gráfico de distribución muestra que la mayor parte de las transacciones se concentra en rangos de venta relativamente bajos o moderados, mientras que existe un menor número de compras con montos elevados.
"""

# Matriz de Correlación
plt.figure(figsize=(8, 6))
corr = df[["edad", "ingreso_mensual", "cantidad", "precio_unitario", "total_venta"]].corr()
sns.heatmap(corr, annot=True, cmap="coolwarm", fmt=".2f")
plt.title("Mapa de Calor de Correlaciones")
plt.show()

# REGRESIÓN LINEAL
print("\n--- Lección 4: Modelo de Regresión ---")
Y = df["total_venta"]
X = df[["edad", "ingreso_mensual", "cantidad", "precio_unitario"]]
X = sm.add_constant(X)

modelo = sm.OLS(Y, X).fit()
print(modelo.summary())

# Métricas
pred = modelo.predict(X)
print(f"\nMSE: {mean_squared_error(Y, pred):.2f}")
print(f"MAE: {mean_absolute_error(Y, pred):.2f}")

# PERSONALIZACIÓN Y SECCIÓN VISUAL
# Variable de tiempo para segmentación


df["fecha_venta"] = pd.to_datetime(df["fecha_venta"])
df["mes"] = df["fecha_venta"].dt.month_name()

Q1 = df["total_venta"].quantile(0.25)
Q3 = df["total_venta"].quantile(0.75)
IQR = Q3 - Q1
lim_inf, lim_sup = Q1 - 1.5 * IQR, Q3 + 1.5 * IQR

df_sin_outliers = df[(df["total_venta"] >= lim_inf) & (df["total_venta"] <= lim_sup)].copy()

print("Columnas en df_sin_outliers:", df_sin_outliers.columns.tolist())


# 1. TRES GRÁFICOS DE DISPERSIÓN (SCATTERPLOTS)

fig, axes = plt.subplots(1, 3, figsize=(18, 5))

# Relación 1: Ingreso vs Venta
sns.scatterplot(data=df_sin_outliers, x="ingreso_mensual", y="total_venta", ax=axes[0], color="blue")
axes[0].set_title("Ingreso mensual vs Venta")

# Relación 2: Cantidad vs Venta
sns.scatterplot(data=df_sin_outliers, x="cantidad", y="total_venta", ax=axes[1], color="green")
axes[1].set_title("Cantidad vs Venta")

# Relación 3: Edad vs Venta
sns.scatterplot(data=df_sin_outliers, x="edad", y="total_venta", ax=axes[2], color="red")
axes[2].set_title("Edad vs Venta")

plt.tight_layout()
plt.savefig("tres_graficos_dispersion.png", dpi=300) # Exportación solicitada
plt.show()

# 2. TRES GRÁFICOS DE DISTRIBUCIÓN (HISTOGRAMAS)
fig, axes = plt.subplots(1, 3, figsize=(18, 5))

sns.histplot(df_sin_outliers["total_venta"], kde=True, ax=axes[0], color="purple")
axes[0].set_title("Distribución: Total Venta")

sns.histplot(df_sin_outliers["ingreso_mensual"], kde=True, ax=axes[1], color="orange")
axes[1].set_title("Distribución: Ingreso Mensual")

sns.histplot(df_sin_outliers["edad"], kde=True, ax=axes[2], color="teal")
axes[2].set_title("Distribución: Edad")

plt.tight_layout()
plt.savefig("tres_graficos_distribucion.png", dpi=300)
plt.show()


plt.suptitle("Relaciones Clave entre Variables", y=1.02)
plt.savefig("relaciones_clave.png", dpi=300)
plt.show()

# 2. Tres Gráficos de Dispersión (Específicos para el informe)
fig, axes = plt.subplots(1, 3, figsize=(18, 5))

sns.scatterplot(x="cantidad", y="total_venta", data=df_sin_outliers, ax=axes[0], color="blue")
axes[0].set_title("Cantidad vs Total Venta")

sns.scatterplot(x="precio_unitario", y="total_venta", data=df_sin_outliers, ax=axes[1], color="green")
axes[1].set_title("Precio Unitario vs Total Venta")

sns.scatterplot(x="ingreso_mensual", y="total_venta", data=df_sin_outliers, ax=axes[2], color="red")
axes[2].set_title("Ingreso Mensual vs Total Venta")

plt.tight_layout()
plt.savefig("tres_graficos_dispersion.png", dpi=300)
plt.show()

# 3. Violinplot (Distribución temporal)
plt.figure(figsize=(12, 6))
sns.violinplot(x="canal_venta", y="total_venta", data=df_sin_outliers, palette="muted")
plt.title("Densidad de Ventas por Mes")
plt.xticks(rotation=45)
plt.savefig("distribucion_ventas_mes.png", dpi=300)
plt.show()

# FacetGrid
g = sns.FacetGrid(df_sin_outliers, col="canal_venta", height=4)
g.map(sns.scatterplot, "ingreso_mensual", "total_venta", alpha=0.6)
g.add_legend()
plt.show()

print("\nPROYECTO COMPLETADO")


print("""
INSIGHTS VISUALES
Existe una relación positiva entre la cantidad de productos
y el total de venta.

La distribución de ventas varía entre meses,
lo que puede reflejar cambios en la demanda.

Las visualizaciones permiten detectar patrones
de comportamiento en las compras del ecommerce.
""")


print("""
RECOMENDACIONES

Segmentar campañas de marketing hacia clientes con mayor ingreso mensual.
Promover productos con mayor valor para aumentar el ticket promedio.
Analizar clientes con compras altas para identificar patrones de fidelización.
""")